nvm install 4.0
nvm install 0.10
npm -g install npm@latest
# Install bower globally
npm install -g bower
bower install
npm install
# Install grunt-cli for running your tests or other tasks
npm install -g grunt-cli
npm test
