language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
before_script:
 - npm -g install npm@latest
# Install bower globally
 - npm install -g bower
 - bower install
 - npm install
# Install grunt-cli for running your tests or other tasks
 - npm install -g grunt-cli

script:
- npm test
